-- ----------------------------------------
-- Añadir metadato LICENSE 
-- ----------------------------------------

ALTER TABLE TB_CONFIGURATIONS ADD LICENSE_FK NUMBER(19);

ALTER TABLE TB_CONFIGURATIONS ADD CONSTRAINT FK_TB_CONFIGURATIONS_LICENSE36
FOREIGN KEY (LICENSE_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID);
