ALTER TABLE TB_CONFIGURATIONS ADD CONSTRAINT CONFIGURATIONS_CODE UNIQUE(CODE);
ALTER TABLE TB_DATA_CONFIGURATIONS ADD CONSTRAINT CONFIGURATIONS_CODE UNIQUE(CONF_KEY);
ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT LOCALE_INTERNATIONAL UNIQUE(LOCALE, INTERNATIONAL_STRING_FK);