-- ---------------------------------------------------------------------------------------------------
-- METAMAC-2215 - [BBDD] Las constraints no pueden ser DEFERRED porque no hay soporte para SQLServer
-- ---------------------------------------------------------------------------------------------------

ALTER TABLE TB_CONFIGURATIONS DROP CONSTRAINT CONFIGURATIONS_CODE;
ALTER TABLE TB_DATA_CONFIGURATIONS DROP CONSTRAINT DATA_CONF_KEY;
ALTER TABLE TB_LOCALISED_STRINGS DROP CONSTRAINT LOCALE_INTERNATIONAL;

ALTER TABLE TB_CONFIGURATIONS ADD CONSTRAINT CONFIGURATIONS_CODE UNIQUE(CODE);
ALTER TABLE TB_DATA_CONFIGURATIONS ADD CONSTRAINT DATA_CONF_KEY UNIQUE(CONF_KEY);
ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT LOCALE_INTERNATIONAL UNIQUE(LOCALE, INTERNATIONAL_STRING_FK);

commit;