-- ###########################################
-- # Create
-- ###########################################

-- Create normal entities
    
CREATE TABLE TB_INTERNATIONAL_STRINGS (
  ID BIGINT NOT NULL,
  VERSION BIGINT NOT NULL
);


CREATE TABLE TB_EXTERNAL_ITEMS (
  ID BIGINT NOT NULL,
  CODE NVARCHAR(255) NOT NULL,
  CODE_NESTED NVARCHAR(255),
  URI NVARCHAR(4000) NOT NULL,
  URN NVARCHAR(4000),
  URN_PROVIDER NVARCHAR(4000),
  MANAGEMENT_APP_URL NVARCHAR(4000),
  VERSION BIGINT NOT NULL,
  TITLE_FK BIGINT,
  TYPE NVARCHAR(255) NOT NULL
);


CREATE TABLE TB_CONFIGURATIONS (
  ID BIGINT NOT NULL,
  CODE NVARCHAR(255) NOT NULL,
  URN NVARCHAR(4000) NOT NULL,
  EXTERNALLY_PUBLISHED BIT NOT NULL,
  UPDATE_DATE_TZ VARCHAR(50),
  UPDATE_DATE DATETIME,
  CREATED_DATE_TZ VARCHAR(50),
  CREATED_DATE DATETIME,
  CREATED_BY NVARCHAR(50),
  LAST_UPDATED_TZ VARCHAR(50),
  LAST_UPDATED DATETIME,
  LAST_UPDATED_BY NVARCHAR(50),
  VERSION BIGINT NOT NULL,
  LEGAL_ACTS_FK BIGINT,
  DATA_SHARING_FK BIGINT,
  CONF_POLICY_FK BIGINT,
  CONF_DATA_TREATMENT_FK BIGINT,
  CONTACT_FK BIGINT,
  LICENSE_FK BIGINT,
  STATUS NVARCHAR(255) NOT NULL
);


CREATE TABLE TB_DATA_CONFIGURATIONS (
  ID BIGINT NOT NULL,
  CONF_KEY NVARCHAR(255) NOT NULL,
  CONF_VALUE NVARCHAR(4000),
  SYSTEM_PROPERTY BIT NOT NULL,
  UPDATE_DATE_TZ VARCHAR(50),
  UPDATE_DATE DATETIME,
  CREATED_DATE_TZ VARCHAR(50),
  CREATED_DATE DATETIME,
  CREATED_BY NVARCHAR(50),
  LAST_UPDATED_TZ VARCHAR(50),
  LAST_UPDATED DATETIME,
  LAST_UPDATED_BY NVARCHAR(50),
  VERSION BIGINT NOT NULL
);


CREATE TABLE TB_LOCALISED_STRINGS (
  ID BIGINT NOT NULL,
  LABEL NVARCHAR(4000) NOT NULL,
  LOCALE NVARCHAR(255) NOT NULL,
  IS_UNMODIFIABLE BIT,
  VERSION BIGINT NOT NULL,
  INTERNATIONAL_STRING_FK BIGINT NOT NULL
);



-- Create many to many relations
    

-- Primary keys
    
ALTER TABLE TB_INTERNATIONAL_STRINGS ADD CONSTRAINT PK_TB_INTERNATIONAL_STRINGS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_EXTERNAL_ITEMS ADD CONSTRAINT PK_TB_EXTERNAL_ITEMS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_CONFIGURATIONS ADD CONSTRAINT PK_TB_CONFIGURATIONS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_DATA_CONFIGURATIONS ADD CONSTRAINT PK_TB_DATA_CONFIGURATIONS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT PK_TB_LOCALISED_STRINGS
	PRIMARY KEY (ID)
;

    

-- Unique constraints

ALTER TABLE TB_INTERNATIONAL_STRINGS
	ADD CONSTRAINT UQ_TB_INTERNATIONAL_STRINGS UNIQUE (ID)
;


ALTER TABLE TB_EXTERNAL_ITEMS
	ADD CONSTRAINT UQ_TB_EXTERNAL_ITEMS UNIQUE (ID)
;


ALTER TABLE TB_CONFIGURATIONS
	ADD CONSTRAINT UQ_TB_CONFIGURATIONS UNIQUE (ID)
;


ALTER TABLE TB_DATA_CONFIGURATIONS
	ADD CONSTRAINT UQ_TB_DATA_CONFIGURATIONS UNIQUE (ID)
;


ALTER TABLE TB_LOCALISED_STRINGS
	ADD CONSTRAINT UQ_TB_LOCALISED_STRINGS UNIQUE (ID)
;



-- Foreign key constraints
    

  
  
ALTER TABLE TB_EXTERNAL_ITEMS ADD CONSTRAINT FK_TB_EXTERNAL_ITEMS_TITLE_FK
	FOREIGN KEY (TITLE_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;

  
ALTER TABLE TB_CONFIGURATIONS ADD CONSTRAINT FK_TB_CONFIGURATIONS_LEGAL_ACTS_FK
	FOREIGN KEY (LEGAL_ACTS_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TB_CONFIGURATIONS ADD CONSTRAINT FK_TB_CONFIGURATIONS_DATA_SHARING_FK
	FOREIGN KEY (DATA_SHARING_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TB_CONFIGURATIONS ADD CONSTRAINT FK_TB_CONFIGURATIONS_CONF_POLICY_FK
	FOREIGN KEY (CONF_POLICY_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TB_CONFIGURATIONS ADD CONSTRAINT FK_TB_CONFIGURATIONS_CONF_DATA_TREATMENT_FK
	FOREIGN KEY (CONF_DATA_TREATMENT_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TB_CONFIGURATIONS ADD CONSTRAINT FK_TB_CONFIGURATIONS_CONTACT_FK
	FOREIGN KEY (CONTACT_FK) REFERENCES TB_EXTERNAL_ITEMS (ID)
;
ALTER TABLE TB_CONFIGURATIONS ADD CONSTRAINT FK_TB_CONFIGURATIONS_LICENSE_FK
	FOREIGN KEY (LICENSE_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;

  
  
  
ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT FK_TB_LOCALISED_STRINGS_INTERNATIONAL_STRING_FK
	FOREIGN KEY (INTERNATIONAL_STRING_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;

  

    
    


    