ALTER TABLE TB_CONFIGURATIONS DROP COLUMN LEGAL_ACTS_URL;
ALTER TABLE TB_CONFIGURATIONS DROP COLUMN DATA_SHARING_URL;
ALTER TABLE TB_CONFIGURATIONS DROP COLUMN CONF_POLICY_URL;
ALTER TABLE TB_CONFIGURATIONS DROP COLUMN CONF_DATA_TREATMENT_URL;