-- ###########################################
-- # Create
-- ###########################################
-- Create pk sequence
    


-- Create normal entities
    
CREATE TABLE TB_INTERNATIONAL_STRINGS (
  ID NUMBER(19) NOT NULL,
  VERSION NUMBER(19) NOT NULL
);


CREATE TABLE TB_EXTERNAL_ITEMS (
  ID NUMBER(19) NOT NULL,
  CODE VARCHAR2(255 CHAR) NOT NULL,
  CODE_NESTED VARCHAR2(255 CHAR),
  URI VARCHAR2(4000 CHAR) NOT NULL,
  URN VARCHAR2(4000 CHAR),
  URN_PROVIDER VARCHAR2(4000 CHAR),
  MANAGEMENT_APP_URL VARCHAR2(4000 CHAR),
  VERSION NUMBER(19) NOT NULL,
  TITLE_FK NUMBER(19),
  TYPE VARCHAR2(255 CHAR) NOT NULL
);


CREATE TABLE TB_CONFIGURATIONS (
  ID NUMBER(19) NOT NULL,
  CODE VARCHAR2(255 CHAR) NOT NULL,
  URN VARCHAR2(4000 CHAR) NOT NULL,
  EXTERNALLY_PUBLISHED NUMBER(1,0) NOT NULL,
  UPDATE_DATE_TZ VARCHAR2(50 CHAR),
  UPDATE_DATE TIMESTAMP ,
  UUID VARCHAR2(36 CHAR) NOT NULL,
  CREATED_DATE_TZ VARCHAR2(50 CHAR),
  CREATED_DATE TIMESTAMP,
  CREATED_BY VARCHAR2(50 CHAR),
  LAST_UPDATED_TZ VARCHAR2(50 CHAR),
  LAST_UPDATED TIMESTAMP,
  LAST_UPDATED_BY VARCHAR2(50 CHAR),
  VERSION NUMBER(19) NOT NULL,
  LEGAL_ACTS_FK NUMBER(19),
  DATA_SHARING_FK NUMBER(19),
  CONF_POLICY_FK NUMBER(19),
  CONF_DATA_TREATMENT_FK NUMBER(19),
  CONTACT_FK NUMBER(19),
  STATUS VARCHAR2(255 CHAR) NOT NULL
);


CREATE TABLE TB_LOCALISED_STRINGS (
  ID NUMBER(19) NOT NULL,
  LABEL VARCHAR2(4000 CHAR) NOT NULL,
  LOCALE VARCHAR2(255 CHAR) NOT NULL,
  IS_UNMODIFIABLE NUMBER(1,0),
  VERSION NUMBER(19) NOT NULL,
  INTERNATIONAL_STRING_FK NUMBER(19) NOT NULL
);



-- Create many to many relations
    

-- Primary keys
    
ALTER TABLE TB_INTERNATIONAL_STRINGS ADD CONSTRAINT PK_TB_INTERNATIONAL_STRINGS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_EXTERNAL_ITEMS ADD CONSTRAINT PK_TB_EXTERNAL_ITEMS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_CONFIGURATIONS ADD CONSTRAINT PK_TB_CONFIGURATIONS
	PRIMARY KEY (ID)
;

ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT PK_TB_LOCALISED_STRINGS
	PRIMARY KEY (ID)
;

    

-- Unique constraints
     
 
 

ALTER TABLE TB_CONFIGURATIONS
    ADD CONSTRAINT UQ_TB_CONFIGURATIONS UNIQUE (UUID)
;

 


-- Foreign key constraints
    

  
  
ALTER TABLE TB_EXTERNAL_ITEMS ADD CONSTRAINT FK_TB_EXTERNAL_ITEMS_TITLE_FK
	FOREIGN KEY (TITLE_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;

  
ALTER TABLE TB_CONFIGURATIONS ADD CONSTRAINT FK_TB_CONFIGURATIONS_LEGAL_A76
	FOREIGN KEY (LEGAL_ACTS_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TB_CONFIGURATIONS ADD CONSTRAINT FK_TB_CONFIGURATIONS_DATA_SH72
	FOREIGN KEY (DATA_SHARING_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TB_CONFIGURATIONS ADD CONSTRAINT FK_TB_CONFIGURATIONS_CONF_PO92
	FOREIGN KEY (CONF_POLICY_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TB_CONFIGURATIONS ADD CONSTRAINT FK_TB_CONFIGURATIONS_CONF_DA43
	FOREIGN KEY (CONF_DATA_TREATMENT_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID)
;
ALTER TABLE TB_CONFIGURATIONS ADD CONSTRAINT FK_TB_CONFIGURATIONS_CONTACT07
	FOREIGN KEY (CONTACT_FK) REFERENCES TB_EXTERNAL_ITEMS (ID)
;

  
ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT FK_TB_LOCALISED_STRINGS_INTE13
	FOREIGN KEY (INTERNATIONAL_STRING_FK) REFERENCES TB_INTERNATIONAL_STRINGS (ID) ON DELETE CASCADE
;

  

    

-- Index


    