create table TB_SEQUENCES (
	SEQUENCE_NAME VARCHAR2(255 CHAR) NOT NULL,
	SEQUENCE_NEXT_VALUE NUMBER(19)
);

ALTER TABLE TB_SEQUENCES ADD CONSTRAINT PK_TB_SEQUENCES
	PRIMARY KEY (SEQUENCE_NAME)
;

ALTER TABLE TB_CONFIGURATIONS ADD CONSTRAINT CONFIGURATIONS_CODE UNIQUE(CODE) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE TB_LOCALISED_STRINGS ADD CONSTRAINT LOCALE_INTERNATIONAL UNIQUE(LOCALE, INTERNATIONAL_STRING_FK) DEFERRABLE INITIALLY DEFERRED;